### ISSUE TITLE
Гръмъ = bush?

### ISSUE THREAD

**Issue by bzaar** [djbpitt/digenis#47]
I'm not an Old Slavic expert but shouldn't the gloss for гръмъ be something like "thunder"?

https://github.com/djbpitt/digenis/blob/c361d74ed966d88c65f0506ec611530c9582d1e7/reader/noun-classes.xhtml#L28

**Comment by djbpitt** [comment]
@bzaar http://www.monumentaserbica.branatomic.com/mikl2/main.php?id=6024&st=1&term=

**Comment by bzaar** [comment]
I stand corrected, thanks!
