### ISSUE TITLE
Is сынъ meant to be listed twice?

### ISSUE THREAD

**Issue by bzaar** [djbpitt/digenis#48]
https://github.com/djbpitt/digenis/blob/c361d74ed966d88c65f0506ec611530c9582d1e7/reader/noun-classes.xhtml#L44-L45

**Comment by bzaar** [comment]
With two different glosses, 'son' and 'tower'.

**Comment by djbpitt** [comment]
Tower: 

- http://www.monumentaserbica.branatomic.com/mikl2/main.php?id=35138&st=1&term=
- http://gorazd.org/gulliver/?recordId=34660

Son: 

- http://www.monumentaserbica.branatomic.com/mikl2/main.php?id=35137&st=1&term=
- http://gorazd.org/gulliver/?recordId=34659

**Comment by bzaar** [comment]
Wow. Amazing. I will shut up now and admire your work in a reverent silence. Sorry for the unsolicited noise.

**Comment by djbpitt** [comment]
@bzaar On the contrary, every "but did you really mean?" is welcome! We all make mistakes, and being asked to check things that don't look quite right counts, at least in my world, as constructive. Thank you for the careful reading!
