### ISSUE TITLE
reconstruct нѣсть from не in negated 3sg "elliptical" perfect?

### ISSUE THREAD

**Issue by robroman** [djbpitt/digenis#69]
Should 3.369 remain не or be expanded to нѣсть? Do negated 3sg "elliptical" perfects exist in the early language?

**Comment by djbpitt** [comment]
Keep as is, which is consistent with our principle that we always include the auxiliary with the pf for 1st and 2nd person, but for 3rd person we follow what the manuscript says at each moment.
