### ISSUE TITLE
такъ / тако

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/digenis#72]
In reading 1, word 88 reads **такъ**:

> И то слово слышавъ отецъ юноши, яко **такъ** глаголетъ юноша

Should we change this to **тако**?

**Comment by robroman** [comment]
Indeed we should! Do you want to take care of it now?
R

**Comment by djbpitt** [comment]
@robroman Yes, thank you! If you can make the change and push, you can close the issue, and I'll generate a new view and upload it when we meet tomorrow.

Meanwhile, I've been working most of today on planning and beginning to implement the more detailed morphological-category tagging we discussed. It looks promising; details about that tomorrow, too!

**Comment by robroman** [comment]
съдѣлано!
