### ISSUE TITLE
оузды?

### ISSUE THREAD

**Issue by djbpitt** [djbpitt/digenis#80]
Reading 1 includes: **И медведь к нему возвратись, разверзь уста своя, хотя его пожрети.**

We have a note (to ourselves) that "Тх has Тх has уды, Tvorogov (prob. < Speranskij) emends to уста, Vaillant 
emends to узды, Tvorogov (prob. < Speranskij) emends to **уста**, Vaillant emends to **узды**. We currently
write **оузды**, following Vaillant; what does that mean

**Comment by robroman** [comment]
In file that I can access, note reads:

I think I sent you Vaillant's note on ǫzgŭ 'coin', let me know if I should resend. 
This passage is a clear reminiscence of Habakkuk 3.14: развeрзутъ ўзды, which Vaillant cites at the start of his note.

**Comment by robroman** [comment]
Forgot to remove the note markers: the note should read
Тх has уды, Tvorogov (prob. < Speranskij) emends to уста, Vaillant emends to узды

**Comment by robroman** [comment]
That is to say, Vaillant emends the Tx reading both more parsimoniously and more correctly (from text-critical POV) than does Tvorogov, who is probably following Speranskij's emendation here

**Comment by robroman** [comment]
Vaillant provides the emendation in his 1955 article on the Slavic Digenis (Le Digenis Slave, Prilozi za knjizevnost, istoriju i folklor 21, 197-288), citing his earlier note on ǫzgŭ 'coin'

**Comment by djbpitt** [comment]
@robroman So "opened the corners of his mouth"? Sounds odd …

**Comment by robroman** [comment]
But text-critically unimpeachable! My favorite translation is Brenton's Septuagint: "they shall burst their bridles"!
It must mean "stretched/gaped/yawned open his mouth to the corners"
